# Generated by Django 4.0.5 on 2022-07-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_comment_date_time_created_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(verbose_name='your Opinion:'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_suggest',
            field=models.BooleanField(default=True, verbose_name='score this product:'),
        ),
    ]
