# Generated by Django 4.0.5 on 2022-08-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_product_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_published',
            field=models.CharField(choices=[('d', 'draft'), ('p', 'published'), ('i', 'investigation'), ('b', 'back')], default='d', max_length=13),
        ),
    ]
