# Generated by Django 4.0.5 on 2022-08-16 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_remove_product_hits'),
    ]

    operations = [
        migrations.CreateModel(
            name='hits_filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.ipaddress', verbose_name='ip_address')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='hits', through='pages.hits_filter', to='pages.ipaddress'),
        ),
        migrations.AddField(
            model_name='hits_filter',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.product', verbose_name='product'),
        ),
    ]
