# Generated by Django 4.0.5 on 2022-08-16 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_hits_filter_product_hits_hits_filter_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hits_filter',
            new_name='hitsfilter',
        ),
        migrations.RenameField(
            model_name='hitsfilter',
            old_name='time_created',
            new_name='timecreated',
        ),
    ]
