# Generated by Django 4.0.5 on 2022-08-19 14:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.STAR_RATINGS_RATING_MODEL),
        ('pages', '0015_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ratings',
            field=models.ManyToManyField(blank=True, related_name='ratings', to=settings.STAR_RATINGS_RATING_MODEL),
        ),
    ]
