# Generated by Django 4.0.5 on 2022-08-19 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_remove_product_ratings_product_ratings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ratings',
            new_name='rating',
        ),
    ]
