# Generated by Django 4.0.5 on 2022-08-20 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
