# Generated by Django 4.0.5 on 2022-09-04 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0024_rename_bookmark_bookmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarks',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark', to='pages.product', verbose_name='post'),
        ),
        migrations.AlterField(
            model_name='bookmarks',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='hitsfilter',
            name='timecreated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='timeview'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='pages.product', verbose_name='post'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cover',
            field=models.ImageField(upload_to='cover', verbose_name='cover'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_time_create',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_created'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_time_edit',
            field=models.DateTimeField(auto_now=True, verbose_name='date_edited'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='hits', through='pages.hitsfilter', to='pages.ipaddress', verbose_name='views'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_published',
            field=models.CharField(choices=[('d', 'draft'), ('p', 'published'), ('i', 'investigation'), ('b', 'back')], default='d', max_length=1, verbose_name='is_pubished'),
        ),
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.CharField(choices=[('empty', 'empty'), ('have', 'have'), ('in_order', 'in_order')], default='have', max_length=8, verbose_name='stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
    ]
