# Generated by Django 4.0.5 on 2022-09-05 09:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_alter_bookmarks_post_alter_bookmarks_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 5, 9, 20, 56, 137461, tzinfo=utc), verbose_name='date_created'),
        ),
    ]
