# Generated by Django 4.0.5 on 2022-08-09 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeuser',
            options={'verbose_name': 'Custome_User'},
        ),
    ]
