# Generated by Django 4.0.5 on 2022-08-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customeuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeuser',
            name='is_author',
            field=models.BooleanField(default=False),
        ),
    ]
