# Generated by Django 4.0.5 on 2022-08-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customeuser_is_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='first_name',
            field=models.CharField(default='sirstname', max_length=200),
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='last_name',
            field=models.CharField(default='lastname', max_length=200),
        ),
    ]
