# Generated by Django 4.0.5 on 2022-08-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customeuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='user_avatar', verbose_name='avatar'),
        ),
    ]
