# Generated by Django 4.0.5 on 2022-08-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customeuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='age',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='first_name',
            field=models.CharField(default='firstname', max_length=200, verbose_name='firstname'),
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='is_author',
            field=models.BooleanField(default=False, verbose_name='is_author'),
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='last_name',
            field=models.CharField(default='lastname', max_length=200, verbose_name='lastname'),
        ),
    ]
