# Generated by Django 4.0.5 on 2022-08-19 07:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('star_ratings', '0004_alter_rating_id_alter_userrating_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='time_edited',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='time_rated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
