# Generated by Django 4.0.5 on 2022-08-19 15:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('star_ratings', '0005_rating_time_edited_rating_time_rated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='time_rated',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 19, 15, 9, 5, 89989, tzinfo=utc)),
        ),
    ]
