# Generated by Django 4.0.5 on 2022-08-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_ratings', '0007_alter_rating_time_rated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='time_rated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
